# Azure DevOps pipeline for running upgrade tests
# Tests upgrading from the previous Strimzi version to the current one
trigger: none

pr: none

parameters:
  - name: BUILD_REASON
    displayName: Build reason
    type: string
    default: "Manual"
  - name: TEST_PROFILE
    displayName: Test profile
    type: string
    default: "upgrade"
  - name: CLUSTER_OPERATOR_INSTALL_TYPE
    displayName: Cluster operator install type
    type: string
    default: "bundle"
    values:
      - bundle
      - helm
      - olm

resources:
  pipelines:
    - pipeline: 'Build'
      source: 'build-pipeline'

extends:
  template: template-pipeline.yaml
  parameters:
    BUILD_REASON: ${{ parameters.BUILD_REASON }}
    TEST_PROFILE: ${{ parameters.TEST_PROFILE }}
    CLUSTER_OPERATOR_INSTALL_TYPE: ${{ parameters.CLUSTER_OPERATOR_INSTALL_TYPE }}
